### ISSUE TITLE
Query with quoted table name

### ISSUE THREAD

**Issue by leo-fmr** [klahnakoski/mo-sql-parsing#130]
This query
```
SELECT x, y
FROM "my_schema.my_table"
```
results in this parse tree with an extra dot in the table name
```
{'from': 'my_schema..my_table', 'select': [{'value': 'x'}, {'value': 'y'}]}
```

**Comment by klahnakoski** [comment]
That is expected behaviour.  The double-quoted string is a literal table name; a name with a dot in it.  The parsed result uses JSON strings to refer to dot-delimited paths; when a dot is required, it is escaped with a double-dot.

For example, without double quotes,

    SELECT * FROM my_schema.my_table

results in

    {'from': 'my_schema.my_table', 'select': "*"}

(with a single dot).
