### ISSUE TITLE
Table names with backquotes are replaced with table names with two dots

### ISSUE THREAD

**Issue by amitaggarwal1** [klahnakoski/mo-sql-parsing#173]
Input: 
SELECT
   customer.c_first_name
FROM `datairis.tpcds_1000.customer` as customer

Output
{"select": {"value": "customer.c_first_name"}, "from": {"value": "datairis..tpcds_1000..customer", "name": "customer"}}

Note the `` in input and the double dots in the output

**Comment by klahnakoski** [comment]
the double dots are intentional.  They are required to distinguish namespace navigation dots from literal dots.  For example

    SELECT * FROM mySchema.myTable

is using the `myTable` from the `mySchema` database.  While

    SELECT * FROM `my.table.with.dots`

is using a table with the literal name of `my.table.with.dots`, with dots in the name.  These can be used together:

    SELECT * FROM mySchema.`my.table.with.dots`

which will get parsed as:

    mySchema.my..table..with..dots

with double dots
