### ISSUE TITLE
quotes vs double quotes

### ISSUE THREAD

**Issue by aosokin** [klahnakoski/mo-sql-parsing#77]
```python
import mo_sql_parsing as msp

q1 = 'SELECT Airline FROM AIRLINES WHERE Abbreviation  =  "UAL"'
q2 = "SELECT Airline FROM AIRLINES WHERE Abbreviation  =  'UAL'"
d1 = msp.parse(q1)
d2 = msp.parse(q2)
```

In `d1`, we get `{'eq': ['Abbreviation', 'UAL']}`, and, in `d2` -  `'eq':['Abbreviation', {'literal': 'UAL'}]`

Is this difference intentional?

**Comment by klahnakoski** [comment]
Sorry for the delay, I missed the message. 

Yes, the difference is intentional:  Double quotes is meant to quote a variable name, while single quotes are meant to quote a literal string.

You can make both single and double quotes mean the same thing, quoting a literal string, by using `parse_mysql`: https://github.com/klahnakoski/mo-sql-parsing#mysql-literal-strings

**Comment by klahnakoski** [comment]
Due to the number of languages using double quotes for string literals, I often forget that they have a different meaning in SQL, and I get stumped by this behaviour for a while until I realize my mistake.

**Comment by klahnakoski** [comment]
I am not sure if this warning should default to on, since I dislike `stderr` message coming out of libraries.

https://github.com/klahnakoski/mo-sql-parsing/commit/ec50e233d9b625114d19f9ff93f0db657d6eae2d#diff-45cfa1ffc9a796dc3d9831bb199aa840eee925c2d1351f2816f3468edd27d443R587-R591
